### ISSUE TITLE
Add setting for whether or not to create unknown users

### ISSUE THREAD

**Issue by bcail** [Brown-University-Library/django-shibboleth-remoteuser#21]
Right now it looks like you have to subclass the backend class to have the backend *not* create Users automatically. Why not add a setting for this, to make it easier to change the functionality?

**Comment by trevoriancox** [comment]
This is consistent with the Django base class, django.contrib.auth.backends.RemoteUserBackend.

https://docs.djangoproject.com/en/1.4/howto/auth-remote-user/

For my purposes, I was better off using the base class directly anyway.

**Comment by bbusenius** [comment]
I like this idea!
