### ISSUE TITLE
Permission groups from shibboleth attributes

### ISSUE THREAD

**Issue by soerenbe** [Brown-University-Library/django-shibboleth-remoteuser#37]
Hello,
in my current Django application I have the problem that every user gets authenticated through our IdP. In my particular scenario the application must have special permission for our normal staff. Students should handled different. (I work for a university).

I came up with a solution to map existing shibboleth attributes to permission groups. To illustrate this see following example. I also used the attributes from the testcase at [test_shib.py](https://github.com/Brown-University-Library/django-shibboleth-remoteuser/blob/master/shibboleth/tests/test_shib.py).

I would add following to my `settings.py`
`SHIBBOLETH_GROUP_ATTRIBUTES = ['Shibboleth-affiliation', 'Shibboleth-isMemberOf']`

When the user get logged in, it will be added to the Groups `['member@college.edu', 'staff@college.edu', 'SCHOOL:COMMUNITY:EMPLOYEE:ADMINISTRATIVE:BASE', 'SCHOOL:COMMUNITY:EMPLOYEE:STAFF:SAC:P', 'COMMUNITY:ALL', 'SCHOOL:COMMUNITY:EMPLOYEE:STAFF:SAC:M']`

If the group does not exists, django-shibboleth-remoteuser will create the groups and add the user to this group. The user also will get removed from every other group not defined in the list above. Now you can add any permission from the application to this groups. 
If `SHIBBOLETH_GROUP_ATTRIBUTES = []` (which I would use for default) there will be no changes to the groups of the user, to ensure backward compatibility.

This is a similar approach like `django-auth-ldap`, where LDAP group attributes may map to Django permission groups (Which I like a lot.).

I definitely will implement this feature. I have the choice to do the generic approach (like described above) or implement my own `ShibbolethRemoteUserBackend`. If you would merge this approach (of course with documentation and tests) I would start next week. What do you think?

**Comment by bcail** [comment]
Sure, you're welcome to do the generic approach and submit it as a PR. We like that it'll be backwards-compatible with an empty SHIBBOLETH_GROUP_ATTRIBUTES by default.

Note: in our experience, the number of different groups in Shibboleth-isMemberOf can be quite large, so there could be many groups created in the django db. Maybe that should just be a note in the documentation, though.

**Comment by soerenbe** [comment]
I added the PR at #39

**Comment by bcail** [comment]
PR merged.
