### ISSUE TITLE
Check for is_active

### ISSUE THREAD

**Issue by helenst** [Brown-University-Library/django-shibboleth-remoteuser#50]
Django's `RemoteUserBackend` (as of 1.11) does not allow login from users with `is_active=False` This seems like a good thing to have in `ShibbolethRemoteUserBackend` too. Would you accept a PR for this?

**Comment by bcail** [comment]
Sure, thanks. Open one and I'll take a look at it. Tests in the PR would be great.

**Comment by helenst** [comment]
I fixed this, so closing it :)
