### ISSUE TITLE
PyPI?

### ISSUE THREAD

**Issue by helenst** [Brown-University-Library/django-shibboleth-remoteuser#53]
This is a neat library - I use it in a couple of projects. It would be great to see it on PyPI and be able to pip install it.

**Comment by m3brown** [comment]
This has been hanging around for a while, I'm hoping this message kickstarts the conversation.

Folks in the community that are using this repo need to go through a few hoops to get django-shibboleth-remoteuser installed in their environments.  If we were to push releases to pypi.org, it would simplify the workflow for the community.

There are a few things that need to happen to make this a reality:
- Get in the habit of updating the version in the setup.py ([link](https://github.com/Brown-University-Library/django-shibboleth-remoteuser/blob/master/setup.py#L87))
- Give someone(s) the authority to the push new releases to pypi

There are plenty of guides for how to do this, such as [this](https://packaging.python.org/tutorials/packaging-projects/) python.org guide.

@bcail and other maintainers, if maintaining a workflow to push to pypi doesn't appeal to you, I'm personally happy to
a) volunteer as a maintainer of the Brown-University-Library repo or
b) publish to pypi from my fork (m3brown), with your blessing. This is certainly not the preferred route, but is not abnormal.

**Comment by bcail** [comment]
@m3brown thanks for the nudge. I'll get it up on pypi.

**Comment by bcail** [comment]
https://pypi.org/project/django-shibboleth-remoteuser/0.11/
