### ISSUE TITLE
In Django 1.6.5 get_fields doesn't exists

### ISSUE THREAD

**Issue by ajira86** [Brown-University-Library/django-shibboleth-remoteuser#54]
I got the following error by running your module to login.

```
'Options' object has no attribute 'get_fields'

Request Method: 	GET
Request URL: 	https://develop.klewel.com/watch/webcasts/
Django Version: 	1.6.5
Exception Type: 	AttributeError
Exception Value: 	

'Options' object has no attribute 'get_fields'

Exception Location: 	/usr/local/lib/python2.7/dist-packages/shibboleth/backends.py in authenticate, line 35
Python Executable: 	/usr/local/bin/uwsgi
Python Version: 	2.7.6
Python Path: 	
```

Apparently Django 1.6.5 doesn't support get_fileds() method but get_all_field_names() exists. Should I propose to you a pull request ?

**Comment by bcail** [comment]
See comment on PR #55.

**Comment by ajira86** [comment]
Thanks for information but it should be better to announce the requirements in README page isn't it ? When I took a first look on it I excepted a Django 1.3 compatibility by reading:

> Middleware for using Shibboleth with Django. Requires Django 1.3 or above for RemoteAuthMiddleware.

**Comment by bcail** [comment]
Yes, good point. A PR updating the README would be welcome.
