### ISSUE TITLE
How is make_profile rewrite working ?

### ISSUE THREAD

**Issue by ajira86** [Brown-University-Library/django-shibboleth-remoteuser#58]
Hello, I try to create a profile in same time of user registration. I found a make_profile class in your middleware with the purpose to be rewritten in case of needs. So, I wrote something like this:

```
from shibboleth.middleware import ShibbolethRemoteUserMiddleware
from app.models.UserProfile import UserProfile

class ShibbolethRemoteUserMiddlewareWithProfile(ShibbolethRemoteUserMiddleware):
    def make_profile(self, user, shib_meta):
        UserProfile.objects.create(user=user)
```

And call this middleware object instead of the original one in my settings.py. But when new user is comming, the profile isn't created and if I put a logger, he will never be triggered.

Perhaps choose I the wrong approach to rewrite this method ?

**Comment by helenst** [comment]
Did you ever figure this out? Your code looks fine to me so if `make_profile` isn't being called when a user logs in, maybe Django isn't loading the middleware correctly.

However, since `make_profile` is called every time a user logs in, your profile creation might be better off in the `configure_user` method of a custom back end so you only create a profile for the user when they first log in.
e.g.

```
from shibboleth.backends import ShibbolethRemoteUserBackend
from app.models.UserProfile import UserProfile

class ShibbolethRemoteUserBackendWithProfile(ShibbolethRemoteUserBackend):
    def configure_user(self, user):
        UserProfile.objects.create(user=user)
        return user
```

**Comment by ajira86** [comment]
By looking on process, I saw that user was created before going in ShibbolethRemoteUserMiddleware.

This because on my Django configuration:

```
MIDDLEWARE_CLASSES = (
    [...]
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.RemoteUserMiddleware', 
    'manage.middleware.ShibbolethRemoteUserMiddlewareWithProfile',
    [...]
)
```

In fact, django.contrib.auth.middleware.RemoteUserMiddleware will create user before shibbloeth middleware. In this case shibboleth middleware will ignore user and profile creation.
