### ISSUE TITLE
Shibboleth is sending null values when users are connecting which is redirecting to login page

### ISSUE THREAD

**Issue by rammohanreddy86** [Brown-University-Library/django-shibboleth-remoteuser#63]
Shibboleth with httpd sso setup integrated with Apex is returning to login page after providing the credentials.

Could you please help on this

**Comment by bcail** [comment]
@rammohanreddy86 could you please add more details about how you've configured things and what error you're seeing? Can you verify that the REMOTE_USER env variable in httpd is set correctly after you log in to Shib?

**Comment by rammohanreddy86** [comment]
We are able to get the good SAML assertions from source but not taking data out of the assertion and converting that to a HTTP header .

**Comment by bcail** [comment]
Please add more details. Do you have a public repository with your code I could look at? What version of Django are you using? How have you configured django-shibboleth-remoteuser?

**Comment by bcail** [comment]
Closing. Please add more details if you'd like to re-open.
