### ISSUE TITLE
Shibboleth headers not coming back when redirect URL is set

### ISSUE THREAD

**Issue by gsidebo** [Brown-University-Library/django-shibboleth-remoteuser#64]
Hey all. We're running into a strange issue where shibboleth login works a charm when no redirect URL is given via the `target` querystring parameter, but when that `target` value is provided, we don't get any of the expected headers in the first request back from shibboleth (`REMOTE_USER`, `SHIB_*` variables, `AUTH_TYPE: shibboleth`, attributes we've requested via the `SHIBBOLETH_ATTRIBUTE_MAP` setting, etc.) and it results in an infinite redirect loop. 

We use Django's `login_required` decorator to protect resources, and our `LOGIN_URL` setting is set to `/Shibboleth.sso/Login`. If we don't explicitly set the `REDIRECT_FIELD_NAME` to `target`, Django uses the default `next`, which shibboleth doesn't understand and is therefore ignored (https://github.com/Brown-University-Library/django-shibboleth-remoteuser/issues/8 discusses this too). When we _do_ set the `REDIRECT_FIELD_NAME` to `target`, the first request coming back from shibboleth is indeed at the correct redirect URL, but that request does not include any of the headers mentioned above. Don't know if it's relevant, but we do see a `_shibsession_*` cookie set. 

Any ideas about what might be causing this? I can provide config settings if needed. Thanks in advance!

**Comment by bcail** [comment]
We have a project where we have created a "login" view, and that url is protected by Shibboleth(a session is required). So the LOGIN_URL doesn't go to the /Shibboleth.sso/Login url, but to our own "login" view:
>  <Location /.../login>
>   AuthType shibboleth
>   Require shibboleth
>   ShibRequireSession on
>  </Location>


> url(r'^login/', LoginView.as_view(), name="login"),


> class LoginView(RedirectView):
> 
>     permanent = False
> 
>     def get_redirect_url(self, *args, **kwargs):
>         self.request.session.pop(LOGOUT_SESSION_KEY, None)
> 
>         next_url = self.request.GET.get('next','')
>         return next_url or reverse('home')

Does that help?

**Comment by gsidebo** [comment]
@bcail We're using nginx, not apache, but your comment made me remember to check the nginx config. Turns out we had only configured the root URL with all the necessary shibboleth settings. Thank you for the indirect tip 😄 I'll close this issue
