### ISSUE TITLE
django-shibboleth-remoteuser won't install to virtual environment

### ISSUE THREAD

**Issue by bradfordk** [Brown-University-Library/django-shibboleth-remoteuser#65]
Hi
I attempted to pip git+shibrepo install while my virtual environment for django project was activated and it still installs to the global python site-packages. Thus, a shibboleth module not found error occurs when running the app. (Testing the app with urls.py pointing to shibboleth.urls and the middleware class added)
Please advise

**Comment by bcail** [comment]
This is what we have in our of requirements.txt files:
git+https://github.com/Brown-University-Library/django-shibboleth-remoteuser.git@v0.7#egg=django-shibboleth-remoteuser
We use it in a virtual env. Does that work for you?

**Comment by bradfordk** [comment]
Yes, it appears to have worked. Thank you
