### ISSUE TITLE
Mock Shibboleth Headers

### ISSUE THREAD

**Issue by precurse** [Brown-University-Library/django-shibboleth-remoteuser#67]
Hello,

I'm trying to create a local development environment to update our Shibboleth application. We want to be able to run it locally without the need for a real SAML IdP.

In the app settings file: https://github.com/Brown-University-Library/django-shibboleth-remoteuser/blob/master/shibboleth/app_settings.py#L11-L12  there's a `SHIB_MOCK_HEADERS` variable that is documented to do exactly what we want. The only issue is that it doesn't seem to do anything (and isn't referenced anywhere else through the code base).

Is there something I'm missing?

Thanks

**Comment by bcail** [comment]
@precurse No, it does look like it's not being used. Possibly it was used in the past - I'm not sure about its history. If you have an idea of what it should be used for, feel free to submit a PR.

**Comment by precurse** [comment]
Thanks

I'm working on an implementation of this and I'll do a PR once I get it merged into the `shibboleth-remoteuser` repo once I get it working

**Comment by lawlesst** [comment]
If I recall correctly, the original idea for this was that in your local app you would subclass ShibolethRemoteUserMiddleware and if this setting was true, you would insert some mock HTTP headers that would authenticate a user. There is something similar [here](https://github.com/Brown-University-Library/easyaccess_project/blob/d59d950fe3e65c18965900cd5c2e4a8b8970bf64/shibboleth/middleware.py#L56), if it helps.

**Comment by rev138** [comment]
@precurse Did you ever complete that PR?

**Comment by precurse** [comment]
> @precurse Did you ever complete that PR?

No I don't think I did, sorry. IIRC, we ended up switching to Flask for our app and never used Django in the end.
