### ISSUE TITLE
	error with  Template tags

### ISSUE THREAD

**Issue by leslie971** [Brown-University-Library/django-shibboleth-remoteuser#69]
Hello

I tried to use the template tags
 but i have this error :u'shibboleth' is not a registered namespace
in the settings.py file the modified parameter is TEMPLATE_CONTEXT_PROCESSORS

django 1.6 

Thanks

**Comment by bcail** [comment]
@leslie971 Django 1.6 is not supported anymore. Please upgrade to Django 1.11 or 2.0 and try again.

**Comment by leslie971** [comment]
I can not upgrade django into Geonode 
is there an old version of this package? is there another solution?

**Comment by bcail** [comment]
Sure, there are tags/releases of this package, and you can try various older ones - don't have to use the most recent.
