### ISSUE TITLE
install old version 

### ISSUE THREAD

**Issue by leslie971** [Brown-University-Library/django-shibboleth-remoteuser#70]
what is the command to install an older version?
I have an error with this command: sudo pip install django-shibboleth-remoteuser-kennydude == 0.4

Could not find a version that satisfies the requirement django-shibboleth-remoteuser-kennydude == 0.4 (from versions: 0.5.macosx-10.11-intel, 0.6, 0.6.1, 0.6.2)

I connect to a server in ssh.

**Comment by bcail** [comment]
@leslie971 Looks like you are using a fork of this package, not this one. Please see https://pypi.org/project/django-shibboleth-remoteuser-kennydude/ and contact kennydude for help.
