### ISSUE TITLE
Problems with Django 2.1

### ISSUE THREAD

**Issue by rbberger** [Brown-University-Library/django-shibboleth-remoteuser#74]
I had to revert back to Django 2.0.8, otherwise, the login never succeeds (even though there is a valid session). I haven't found any error/warning in the logs. Seems to be silently failing and going back to the anonymous user. Reverting back to 2.0.8, reloading apache and refreshing the page reloads the authenticated page.

**Comment by bcail** [comment]
https://github.com/Brown-University-Library/django-shibboleth-remoteuser/releases/tag/v0.10
