### ISSUE TITLE
Unknown AssertionConsumerServiceURL Shibboleth.sso/SAML2/POST

### ISSUE THREAD

**Issue by lchiriac** [Brown-University-Library/django-shibboleth-remoteuser#78]
I had configured everything, but getting an unknown url error after a successful login, while being redirected back to my protected page: '**_Unknown AssertionConsumerServiceURL_** '

<samlp:Status><samlp:StatusCode Value=\"urn:oasis:names:tc:SAML:2.0:status:Requester\"/><samlp:StatusMessage>Unknown AssertionConsumerServiceURL https://mywebsite/Shibboleth.sso/SAML2/POST</samlp:StatusMessage></samlp:Status>

I found references to **SAML2/POST** in the **C:\opt\shibboleth-sp\etc\shibboleth\protocols.xml**, is this not supposed to be implemented by Shibboleth.sso intrinsically? 

Not sure if I need to implement that or not... somehow. Any thoughts appreciated.

 -thanks a lot!

**Comment by bcail** [comment]
Hi @lchiriac - this may be an issue in your Shib config (unrelated to this package). You might want to try the Shib user list: https://www.shibboleth.net/community/lists/.

**Comment by lchiriac** [comment]
closing issue, found a workaround later, and forgot to close this
