### ISSUE TITLE
urllib quote library import is incorrect for python 3

### ISSUE THREAD

**Issue by MLHale** [Brown-University-Library/django-shibboleth-remoteuser#85]
When running the shib tests using the shibboleth app, the urllib throws an error indicating the quote library is not being imported correctly

**Comment by rev138** [comment]
FYI this problem still exists in `context_processors.py` 

```python
5. from django.utils.six.moves.urllib_parse import quote
```

**Comment by bcail** [comment]
Should be fixed.
