### ISSUE TITLE
0.12 release?

### ISSUE THREAD

**Issue by rev138** [Brown-University-Library/django-shibboleth-remoteuser#88]
Hi,

0.11 is incompatible with Django 3.0+ due to the removal of `django.utils.six`, but the most recent fixes merged into master seem to address this. Any idea when we can expect an official 0.12 release available via PyPi? It's much easier to bundle into a requirements.txt file that way.

Thanks!

**Comment by bcail** [comment]
Done: https://pypi.org/project/django-shibboleth-remoteuser/.
